import { appTools, defineConfig } from '@modern-js/app-tools';
import { garfishPlugin } from '@modern-js/plugin-garfish';
import { statePlugin } from '@modern-js/plugin-state';

export default defineConfig({
  runtime: {
    router: true,
    state: true,
    masterApp: {},
  },
  source: {
    // automatically generated asynchronous boundary via Dynamic Import, allowing the page code to consume remote modules generated by the module federation.
    enableAsyncEntry: true,
  },
  output: {
    disableTsChecker: true,
  },
  tools: {
    postcss: {
      plugins: [require('tailwindcss'), require('autoprefixer')],
    },
    rspack: (config, { rspack, appendPlugins }) => {
      appendPlugins([
        // new rspack.container.ModuleFederationPlugin({
        //   name: 'host',
        //   remotes: {
        //     app1: 'mfe2@http://localhost:8081/static/js/remoteEntry.js',
        //   },
        //   shared: {
        //     react: { singleton: true },
        //     'react-dom': { singleton: true },
        //   },
        // }),
      ]);
    },
  },
  plugins: [
    appTools({
      bundler: 'rspack',
    }),
    statePlugin(),
    garfishPlugin(),
  ],
});
